### ISSUE TITLE
Swapchain recreation - happens multiple times on resize

### ISSUE THREAD

**Issue by MatejSakmary** [Ipotrick/Daxa#13]
In the current implementation Daxa checks if the swapchain is out of date two times. FIrst in **impl_swapchain.cpp** when acquiring new immage, second in **impl_device.cpp** when presenting the image to the screen. I find this innitself a bit weird as I believe the check should be done only once per frame ( when acquiring the immage ). 

In the provided examples a third check is done by the user via the use of glfw window resized callback. This in turn calls the recreation of the swapchain again (with wrong values - but they get ignored by the daxa implementation anyways so it has no effect).

**Comment by MatejSakmary** [comment]
I created some very crude logging into the console and I it gives pretty good hint as to what what happens. This is one of the frames that I logged when I was continually resizing the window:

- Swapchain acquires the immage wihtout any problems
- **Draw()** tries to present to the screen and present in **impl_device.cpp** detects swapchain out of date
    - **impl_device.cpp** calls **impl_swapchain.cpp** **recreate()** function recreates swapchain with dimenstions 1480 x 600
- GLFW detects window resize with dimensions 1460 x 600 ( I believe GLFW is delayed here - note that I was continously expanding the window)
- User application (**main.cpp** in mandelbrot in my case) calls  **resize()** located in **impl_swapchain.cpp**
    - **resize()** calls **recreate()**
        - **recreate()** overwrites the values provided by **resize()** by current *PhysicalDeviceSurfaceCapabilities*
        - **recreate()** recreates the swapchain with dimensions 1480 x 600

**Comment by GabeRundlett** [comment]
This is very interesting, to be sure. I will do some local testing now. I'd definitely like to get this resizing stuff sorted

**Comment by GabeRundlett** [comment]
So for anyone who sees this in the future, it actually turns out that swapchain recreation is an underspecified portion of the Vulkan spec at the moment, and the only way to "correctly" do it is to wait idle before creating a new one. Another note is that acquisition of the swapchain image actually is a call that does nothing because of some vendor stuff (more underspecified Vulkan), so it's not enough to rely on the swapchain being invalidated. So we force the user to prompt Daxa to recreate the swapchain if a window management event comes up that should affect it.
